name: 01 - Main CI
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:

  sast:
    name: SAST
    uses: ./.github/workflows/sast.yml
    secrets: inherit