name: 01 - Main CI
on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  actions: read
  security-events: write
  packages: write

jobs:
  sast-api:
    name: SAST-API
    uses: ./.github/workflows/sast-api.yml
    secrets: inherit
  sast-web:
    name: SAST-WEB
    uses: ./.github/workflows/sast-web.yml
    secrets: inherit